site_name: Docker Training
site_description: 'Basic Docker Training And Best Practices'
site_author: 'wundertax'
#repo_name: 'wundertax/documentation'
#repo_url: 'https://github.com/wundertax/documentation'
theme:
  name: 'material'
  logo: 'images/logo.svg'
  favicon: 'images/favicon.png'
  palette:
    primary: 'Blue'
    accent: 'Blue'
    #  feature:
    #tabs: true

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true


# Repository
repo_name: wundertax/docker-training
repo_url: https://github.com/wundertax/docker-training
edit_uri: ""

# Copyright
copyright: 'Copyright &copy; 2018 - wundertax'

# Page tree
pages:
  - Home: index.md
  - Dockerfiles:
     - Best Practices: dockerfiles/best-practices.md
     - Linting: dockerfiles/linting.md
  - Exercises:
     - Static Website: exercises/static-site.md
     - Bind Volume: exercises/bind-volume.md
     - Docker Compose: exercises/compose-wordpress.md
  - Contributing: contribute.md
  - Credits: credits.md
